### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by faimasitumorang** [pars11/Oquotes#1]
Hi, I want to contribute to this repo, i want to create logo and icons for this project. It will be free for you. 
Do you want to see the logo?

**Comment by pars11** [comment]
Hello, thank you for your interest. Soon I will open up a task for it on Utopian. When I open task, you can submit your designs. During this time you can reach me via discord (pars11) or you can follow [me](https://steemit.com/@pars11).

**Comment by faimasitumorang** [comment]
Okay, I will wait for the task request from you

2018-04-04 2:41 GMT+07:00 Samet Aydın <notifications@github.com>:

**Comment by pars11** [comment]
Task request is approved.
