### ISSUE TITLE
(Task Request) Logo for Oquotes

### ISSUE THREAD

**Issue by artjeck** [pars11/Oquotes#10]
Hi I am a graphic designer, I want to contribute to your request task, Before I start I want to get your permission 

This is my logo design
![untitled-2](https://user-images.githubusercontent.com/38141262/38487707-4b56a28a-3c0b-11e8-88b6-1428d29e5124.jpg)

**Comment by pars11** [comment]
Of course you can start, please share your post until deadline to 10 April 18:00:00 (UTC)

**Comment by artjeck** [comment]
thank for your feedback sir

**Comment by artjeck** [comment]
### Benefit/Improvement :
I created this logo with a concept like Owner Want, that is with (") Quotes.Because the concept of quotes is the main core in making this logo. Then I combine with the shape and rectangle for the logo looks simple and elegant.I also use colors that are easy to see, meaning the logo color is not too dark and not too bright. I'm sure this logo is able to make other users of this application satisfied.I hope you like it. 😃 
You can see The original file [here](https://drive.google.com/drive/folders/17tbghWnywmW2NoMU_AzX3CeWpKo6GgoW?usp=sharing)
![logomark](https://user-images.githubusercontent.com/38141262/38511700-2362d44a-3c53-11e8-91bd-2b49f664f772.jpg)
![logotext](https://user-images.githubusercontent.com/38141262/38511702-23c13e04-3c53-11e8-968b-b081206b76e2.jpg)
![logotext-all](https://user-images.githubusercontent.com/38141262/38511703-24011e0c-3c53-11e8-8983-a54ea959984b.jpg)
![mock up 1](https://user-images.githubusercontent.com/38141262/38511705-24409f28-3c53-11e8-8543-38e100614271.jpg)
![mock up 2](https://user-images.githubusercontent.com/38141262/38511707-24892130-3c53-11e8-8f95-2c80686e7cdd.jpg)
![mock up 3](https://user-images.githubusercontent.com/38141262/38511708-24ca71c6-3c53-11e8-978b-9be5aedc3e39.jpg)
![proof of work](https://user-images.githubusercontent.com/38141262/38511709-2504c718-3c53-11e8-96a3-a54563626c1d.jpg)

**Comment by pars11** [comment]
Thank you for your design. Logo choice was made. https://steemit.com/utopian-io/@pars11/need-a-logo-for-oquotes
