### ISSUE TITLE
Logo Design for Oquotes

### ISSUE THREAD

**Issue by mdnazmulhasan27771** [pars11/Oquotes#11]
This is my logo design for your project i hope you like this..

https://utopian.io/utopian-io/@mdnazmulhasan/logo-design-for-oquotes

![untitled-9-01](https://user-images.githubusercontent.com/35112507/38494360-7a1d0170-3c17-11e8-8be5-c85ee7724e7e.jpg)

Thank you.

**Comment by pars11** [comment]
Thank you for your design. Logo choice was made. https://steemit.com/utopian-io/@pars11/need-a-logo-for-oquotes
