### ISSUE TITLE
Character Logo Design for Oquotes App

### ISSUE THREAD

**Issue by anaufalm** [pars11/Oquotes#12]
Hi, look at my design logo for you [here](https://utopian.io/utopian-io/@naufal/character-logo-design-for-oquotes-app), hope you like it. ;)

![Oquotes.png](https://cdn.utopian.io/posts/45b724a21493dfbe0971dd17d8c0f3163dc4Oquotes.png)

**Comment by pars11** [comment]
Thank you for your design. Logo choice was made. https://steemit.com/utopian-io/@pars11/need-a-logo-for-oquotes
