### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by abdulmalikkhan655** [pars11/Oquotes#19]
Hello, @pars11I want to contribute in "Oquotes" so i  want to designed a new logo for "Oquotes" and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.
if you want i will send you my design

contact me on facebook for fast delivary 
https://www.facebook.com/abdulmalikkhan655

**Comment by pars11** [comment]
Oquotes have a logo thanks.

https://steemit.com/utopian-io/@linade/2-simple-and-memorable-logos-for-oquotes
https://steemit.com/utopian-io/@pars11/need-a-logo-for-oquotes
