### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by jbeguna04** [pars11/Oquotes#2]
Hi, I have read your task request about your project for OQuotes. And I making this issue to evaluate my proposal. I have created my designs about this project. Thank You! 
#### Logo Designs
![image](https://user-images.githubusercontent.com/35353768/38417052-7061f50a-39c9-11e8-90b4-18eb26ea69c2.png)
#### Icon Variation
![image](https://user-images.githubusercontent.com/35353768/38419519-60e3aff6-39d3-11e8-9cd5-0daa61988196.png)
#### Logo Types
![logotypes](https://user-images.githubusercontent.com/35353768/38451036-fbd5312e-3a5a-11e8-9858-64b432938bc1.png)
#### MockUp
![mockup1](https://user-images.githubusercontent.com/35353768/38451043-07278478-3a5b-11e8-8375-3fbcd696551b.png)

**Comment by pars11** [comment]
Thanks jbeguna04 will be evaluated.

**Comment by jbeguna04** [comment]
Anytime pars11, Im honored to contribute for your project

**Comment by pars11** [comment]
Thank you for your design. Logo choice was made. https://steemit.com/utopian-io/@pars11/need-a-logo-for-oquotes
