### ISSUE TITLE
Proposal of logo and icon for the application

### ISSUE THREAD

**Issue by richardbmx** [pars11/Oquotes#3]
Hello happy day I leave my proposal to fulfill the task of utopian logo if you want to make any changes do not hesitate to write greetings.

![logo56](https://user-images.githubusercontent.com/35604837/38447935-b0b10c0e-39ce-11e8-9bec-a8fe4ccb0191.png)

Variation

![logo5622](https://user-images.githubusercontent.com/35604837/38448139-2bb90360-39d0-11e8-80b4-c0d1ac9f6e01.png)

**Comment by pars11** [comment]
Thanks richard will be evaluated.

**Comment by pars11** [comment]
Thank you for your design. Logo choice was made. https://steemit.com/utopian-io/@pars11/need-a-logo-for-oquotes
