### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by dibon-github** [pars11/Oquotes#4]
Hi im a graphics designer, I had seen your task request on utopian here are my ideas for your logo.

![1](https://user-images.githubusercontent.com/31919065/38447953-60e62b2c-3a33-11e8-811b-c4f140c9750c.png)
![2](https://user-images.githubusercontent.com/31919065/38447954-611cdcd0-3a33-11e8-9b34-4926ce1f353b.png)
![3](https://user-images.githubusercontent.com/31919065/38447955-61581b4c-3a33-11e8-8db1-bd01d01d23fe.png)
![4](https://user-images.githubusercontent.com/31919065/38447956-618ec610-3a33-11e8-9a05-fdc1117357e3.png)
![5](https://user-images.githubusercontent.com/31919065/38447952-60aa6dda-3a33-11e8-9e03-425e054ebf45.png)

**Comment by dibon-github** [comment]
https://utopian.io/utopian-io/@baa.steemit/logo-proposal-for-oquotes
Here is the link to my proper proposal sir. Please have time to take a look.

**Comment by pars11** [comment]
Thanks dibon will be evaluated.

**Comment by pars11** [comment]
Thank you for your design. Logo choice was made. https://steemit.com/utopian-io/@pars11/need-a-logo-for-oquotes
