### ISSUE TITLE
my Icon/Logo design for Oquotes

### ISSUE THREAD

**Issue by Tobaloidee** [pars11/Oquotes#6]
Hi Sir @pars11  ,  here's the link to my design..

https://utopian.io/utopian-io/@tobaloidee/my-icon-logo-design-contribution-for-oquotes

![comment](https://user-images.githubusercontent.com/36028424/38463965-e06fe2ac-3b37-11e8-8ad1-cfbde4ebf904.png)

Best regards!
Tobaloidee

**Comment by pars11** [comment]
Thanks Tobaloidee will be evaluated

**Comment by pars11** [comment]
Thank you for your design. Logo choice was made. https://steemit.com/utopian-io/@pars11/need-a-logo-for-oquotes
