### ISSUE TITLE
Logo for Oquotes

### ISSUE THREAD

**Issue by mirzazulfan** [pars11/Oquotes#7]
Hi pars11 here is my contribution, hope you like it. Thanks
![tes](https://user-images.githubusercontent.com/36124339/38478555-b07b01c4-3be3-11e8-903f-1b34e77fa6d7.png)

https://steemit.com/utopian-io/@midun/logo-for-oquotes

Best regard, Salam

**Comment by pars11** [comment]
Thank you for your design. Logo choice was made. https://steemit.com/utopian-io/@pars11/need-a-logo-for-oquotes
