### ISSUE TITLE
2 Logo proposals for Oquotes

### ISSUE THREAD

**Issue by linadesteem** [pars11/Oquotes#8]
here are 2 icon proposals for your app sir. simple and memorable as youasked sir
https://utopian.io/utopian-io/@linade/2-simple-and-memorable-logos-for-oquotes

![asset 30_1](https://user-images.githubusercontent.com/35618068/38481196-bb45e352-3bf3-11e8-95cc-61387586c6b9.png)
![asset 37](https://user-images.githubusercontent.com/35618068/38481197-bb99e1a0-3bf3-11e8-9419-385889b33a7c.jpg)
![asset 38](https://user-images.githubusercontent.com/35618068/38481198-bc08cb06-3bf3-11e8-8de2-990b51c5e64b.jpg)

**Comment by pars11** [comment]
Thank you for your design. Logo choice was made. https://steemit.com/utopian-io/@pars11/need-a-logo-for-oquotes
