### ISSUE TITLE
Logo Purposal For Oquotes.

### ISSUE THREAD

**Issue by AbdulmananAkmal** [pars11/Oquotes#9]
hey Sir, With all due respect, I want to purpose a logo for your app on a given task request.
https://utopian.io/utopian-io/@pars11/need-a-logo-for-oquotes

**JPG FILE**

![800mul800yellowred](https://user-images.githubusercontent.com/36930583/38486530-c5065ba8-3bf6-11e8-82e2-7284115d7843.png)

**Splash**

![splash](https://user-images.githubusercontent.com/36930583/38486586-ef158ab8-3bf6-11e8-9f4a-01ded5b5232b.png)

COLOR MANIPULATION CAN BE DONE ON YOUR REQUEST :)

![800mul800](https://user-images.githubusercontent.com/36930583/38484643-b76c24ec-3bf0-11e8-9af5-b8da6ad64505.jpg)

**PNG FILE**

![800mul800](https://user-images.githubusercontent.com/36930583/38484699-dcf06372-3bf0-11e8-8896-708319f9ac6a.png)

 **RED AND BLACK.**

![800mul800redblack](https://user-images.githubusercontent.com/36930583/38484979-c1f0ea1e-3bf1-11e8-8108-c981fe31f745.png)

![800mul800redblackpng](https://user-images.githubusercontent.com/36930583/38484987-c93f7948-3bf1-11e8-9a16-66d8a694d379.png)

Waiting for your reply Sir!

**Comment by AbdulmananAkmal** [comment]
![Splash.jpg](https://steemitimages.com/DQmdi5NU9Kf14TrjtHnvhJYzsVBfyY44zZp6P5NcW4CTmeA/Splash.jpg)

**Comment by pars11** [comment]
Thank you for your design. Logo choice was made. https://steemit.com/utopian-io/@pars11/need-a-logo-for-oquotes
